version: 2.1

orbs:
  node: circleci/node@6.3.0

jobs:
  unit-tests:
    executor:
      name: node/default
      tag: '16.14'
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm test
          name: Unit tests

  lint:
    executor:
      name: node/default
      tag: '16.14'
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run lint
          name: Linter

workflows:
  test_and_lint:
    jobs:
      - unit-tests
      - lint
