version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  unit-tests:
    executor:
      name: node/default
      tag: '16.14'
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm test
          name: Unit tests

workflows:
  build_and_test:
    jobs:
      - unit-tests
