version: 2.1

orbs:
  node: circleci/node@7.2.1

jobs:
  unit-tests:
    executor:
      name: node/default
      tag: "20.19.5"
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm test
          name: Unit tests

  lint:
    executor:
      name: node/default
      tag: "20.19.5"
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run lint
          name: Linter

workflows:
  test_and_lint:
    jobs:
      - unit-tests
      - lint
